<a href="https://colab.research.google.com/github/pannhapat/udemy_datascience/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the relevant libraries


In [0]:
import numpy as np

Create a tensor

In [0]:
m1 = np.array([[5,12,6],[-3,0,24]])
m1

In [0]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

In [8]:
t = m1
m2


array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [10]:
t=np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 24]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Checking its shap

In [13]:
t.shape

(2, 2, 3)

Manually createing a tensor

In [0]:
t_manual = np.array([[[5,12,6],[-30,0,14]],[[9,8,7],[1,3,-5]]])

In [15]:
t_manual

array([[[  5,  12,   6],
        [-30,   0,  14]],

       [[  9,   8,   7],
        [  1,   3,  -5]]])